# Generated by Django 5.0.6 on 2025-12-12 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.FileField(upload_to='docs/')),
                ('tamanio', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoPDF',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_documentos.documento')),
                ('tiene_etiquetas', models.BooleanField(default=False)),
            ],
            bases=('gestion_documentos.documento',),
        ),
        migrations.CreateModel(
            name='ConversorFormato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_conversion', models.DateField(auto_now_add=True)),
                ('documento_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_documentos.documentopdf')),
            ],
        ),
    ]
