# Generated by Django 5.0.6 on 2026-01-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADO', 'Validado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='documentopdf',
            name='metadatos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentopdf',
            name='numero_paginas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tamanio',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='ConversorFormato',
        ),
    ]
