# Generated by Django 5.0.6 on 2026-01-02 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documentos', '0002_documento_estado_documentopdf_metadatos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoHTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='html_generados/')),
                ('etiquetas_semanticas', models.TextField(blank=True, help_text='Lista de etiquetas usadas (ej: main, nav, p)')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('nivel_accesibilidad', models.CharField(default='A (Básico)', max_length=50)),
                ('cantidad_etiquetas', models.IntegerField(default=0)),
                ('lenguaje_html', models.CharField(default='es', max_length=5)),
                ('documento_fuente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='html_generado', to='gestion_documentos.documentopdf')),
            ],
        ),
        migrations.CreateModel(
            name='ConversorFormato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_conversion', models.DateTimeField(auto_now_add=True)),
                ('tiempo_ejecucion', models.FloatField(blank=True, null=True)),
                ('documento_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_documentos.documentopdf')),
            ],
        ),
    ]
